Feature branch
Ellyboi/Code-Review-Practice pull request #1
Opened 2022-12-04 03:28 UTC by Ellyboi

Linters configuration

2022-12-05 18:37 UTC, Ellyboi reviewed
#linters passed 👍  #GitHub flow 👍  #docummentation 👍  

# Changes required ♻️ 
While you have done a great work, some codes need adjustment, kindly remove them and do the necessary corrections for your project to be approved and move to next stage.

2022-12-05 18:37 UTC, Ellyboi commented on index.html
>      </section>
I think the image you put in seperate section here should have put in separate '<div>'.

2022-12-05 18:37 UTC, Ellyboi commented on style.css
>    justify-content: space-between;
please, some codes here are unnecessary to your code, kindly remove them not to have a complex codes

2022-12-05 19:01 UTC, joskalenda commented on index.html
>      </section>
- [ ] Please write meaningful review comments for the student to understand why he should follow your suggestion. and if need be, provide to the student with a better way to it in the future

2022-12-05 19:07 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Ellyboi , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media3.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif"/> |

## Highlights

- [ ]...✅ Greate use of the inline comment 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please read the comments under your review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 19:13 UTC, joskalenda commented on style.css
>    justify-content: space-between;
- [ ] Same as here, please address why the student should remove this code, you can try telling to the student that the duplicated lines of code are not professional and clean.

2022-12-05 20:48 UTC, Ellyboi reviewed
**Highlights** 
Your project looks impressive 👍
All linter checks are passing ✔️
Reasonable commits 💯 

**Required Changes** ♻️
You did great work following the Figma to implement your project, Please, kindly follow and do the necessary corrections, this will make your project look exactly the way it was suggested and professional

2022-12-05 20:48 UTC, Ellyboi commented on style.css
>    justify-content: space-between;
Your code looks good here, please some codes are unnecessary in your codes, kindly remove them, this will make your code simple and easy to access

2022-12-05 20:48 UTC, Ellyboi commented on index.html
>      </section>
You have done a great job here !, but I will suggest you should use 'div' to replace 'section' this will make your code looks more professional

2022-12-05 21:06 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @Ellyboi , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/> |

### Highlights
✅ ...Polite communication with the  student
✅ ...Great use of the inline comment

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 21:19 UTC, merged

2023-02-20 18:10 UTC, Abenezer-Tilahun reviewed
Hi @Ellyboi 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ Good job for suggest the comments polite, 
✔️ Good job for using the GitHub inline features.
✔️ Good Job For Implementing Review your project from the past.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._